config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "static_pages#index"

  get 'sobre', to: 'static_pages#sobre'
  get 'contato', to: 'static_pages#contato'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'

  

  resources :users, only:[:new, :create, :show, :edit, :update]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i 

    validates :name, presence: true, length: {maximum: 50}
    validates :password, length: {minimum: 6}
    validates :email, presence: true, length: { maximum: 255 },
                                      format: { with: VALID_EMAIL_REGEX },
                                      uniqueness: { case_sensitive: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include SessionsHelper

    private
        def require_logged_in_user
            unless user_signed_in?
                flash[:danger] = 'Área restrita. por favor, realize o Login.'
                redirect_to entrar_path
            end
        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to user_path(current_user) if user_signed_in?
  end

  def create
    user = User.find_by(email: params[:session] [:email].downcase)
    if user && user.authenticate(params[:session] [:password])
      sign_in(user)
      redirect_to user_path(user)
    else  
      flash.now[:danger] = 'Email ou senha incorretos.'
      render 'new'
    end  
  end

  def destroy
    sign_out
    flash[:success] = 'Logout realizado com sucesso!'
    redirect_to entrar_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def contato
    end

    def sobre
    end

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_logged_in_user, only: [:edit, :update, :destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = 'Usuário cadastrado com sucesso!'
            redirect_to root_url
        else  
            render 'new'
        end
        
    end

    def edit
    end

    def update
        if current_user.update(user_params)
            flash[:success] = "Dados atualizados com sucesso!"
            redirect_to user_path(current_user)
        else
            render 'edit'
        end
        
    end


    private
        def user_params
            params.require(:user).permit(:email, :name, :password, :password_confirmation)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
        session[:user_id] = user.id
    end

    def sign_out
        session.delete(:user_id)
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def user_signed_in?
        !current_user.nil?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="">
        <div class= "alert alert-danger">
        Ops! Encontramos <%= pluralize(object.errors.count, 'erro', 'erros') %>
            <ul>
                <% object.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %> 
            </ul>
        </div>
    </div> 
<% end %>       

app/views/layouts/_footer.html.erb
<footer>
  <small>
  <% if !user_signed_in? %>
    <%= link_to 'Reserva de Salas. Teste N2 ESL.', root_path %>
    <% else %>
    <%= link_to 'Reserva de Salas. Teste N2 ESL.', current_user %>
    <% end %>
    
  </small>

  <nav>
    <ul>
      <li>
        <%= link_to 'Sobre', sobre_path %>
      </li>
      <li>
        <%= link_to 'Contato', contato_path %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar fixed-top navbar-inverse">
  <div class= "container-fluid">
        <% if !user_signed_in? %>
        <%= link_to 'Meeting Room', root_url, class: 'navbar-brand' %>
        <% else %>
        <%= link_to 'Meeting Room', current_user, class: 'navbar-brand' %>
        <% end %>
       <div class="collapse navbar-collapse" id="expanded-menu">

    <ul class="nav navbar-nav navbar-right">

      <% if !user_signed_in? %>
        <li>
          <%= link_to 'Entrar', entrar_path %>
      </li>
      <% else %>
            <li class= "user_show_name">
              <%= link_to current_user.name, current_user %>
            </li>
            <li>
              <%= link_to 'Editar', edit_user_path(current_user) %>
            </li>
            <li class="divider" role="separator"></li>
            <li>
              <%= link_to 'Sair', sair_path, method: :delete %>
            </li>
          </ul>
        </li>
      <% end %>

    </ul>

  </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="sortcut icon" type="image/png" href="https://cdn.iconscout.com/icon/free/png-256/calendar-1479857-1252980.png">
    <title> Meeting Room</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header'%>

    <div class="container">
    <% flash.each do |message_type, message| %>
       <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
         <button type="button" class="close" data-dismiss="alert" aria-label="Close">
           <span aria-hidden="true">&times;</span>
         </button>
         <%= message %>
       <% end %>
     <% end %>
    <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/static_pages/contato.html.erb
<h1>Contato</h1>

<p>
  E-mail profissional para contato: <b>lfreitas@eslsistemas.com.br</b>
</p>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1 class="texture">Meeting Room</h1>
  <h2 class="texture">
    Reserve, visualize e edite horários de uma Sala de Reuniões!
  </h2>
  <p>
    <%= link_to 'Crie Sua Conta', new_user_path, class: 'btn btn-primary btn-lg' %>
  </p>
</div>

app/views/static_pages/sobre.html.erb
<h1>Sobre</h1>

<p>
  Atualmente atuo como Analista de Suporte (Estágio) referente ao Sistema ESL Cloud, e busco novos desafios e aprendizados na equipe de N2!
</p>

app/views/users/_form.html.erb
<%= render 'layouts/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Editar Perfil</h1>
  </div>

  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <%= form_for current_user do |f| %>
      <%= render 'form', f: f %>
      <%= f.submit 'Atualizar', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class= "row">
    <div class= "col-xs-12">
        <h1>Cadastrar-se</h1>
    </div>

    <div class= "col-md-6 col-md-offset-3 col-xs-12">
        <%= form_for @user do |f| %>
        <%= render 'layouts/error_messages', object: f.object %>

            <div class="form-group">
                <%= f.label :nome %>
                <%= f.text_field :name, class:'form-control' %>
            </div>

            <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: "form-control"%>
            </div>

            <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>

            <%= f.submit 'Cadastrar', class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<h1> Olá, <%= current_user.name%> </h1>

<section class="section">
   <div id="calendar"></div>
</section>